### ISSUE TITLE
SCTP data channels

### ISSUE THREAD

**Issue by Nuwanda** [oztu/p#10]
Since I was having trouble with the limitations of rtp data channels, which P creates by default, I've stopped using that default and tried to create SCTP data channels instead. Unfortunately since that change no messages are delivered between peers, no errors are reported either. If I change the library to remove the default RTP option, your examples don't work either.
Do you see any reason why this might be happening?

**Comment by oztu** [comment]
Closing this since the latest update makes data channels reliable by default.
